"unit_added"		{
		"camera_guy"	{	"1"	"camera_passive"
		}
		"npc_cosmetic_pet"	{
		}
		"npc_dota_creature_basic_zombie"	{
		}
		"npc_dota_creature_berserk_zombie"	{	"1"	"zombie_berserk"
		}
		"npc_dota_custom_creep_01_1"	{	"1"	"my_debuff"
		}
		"npc_dota_custom_creep_01_2"	{
		}
		"npc_dota_custom_creep_10_1"	{	"1"	"my_lava_boom"		"2"	"my_fisure"		"3"	"ogre_tank_jump_smash"		"4"	"my_boss_towers"								"7"	"my_gem_datadriven"		"8"	"my_boss_hpdar"
		}
		"npc_dota_custom_creep_10_2"	{
		}
		"npc_dota_custom_creep_11_1"	{	"1"	"ursa_fury_swipes_datadriven"
		}
		"npc_dota_custom_creep_12_1"	{	"1"	"my_macropyre_datadriven"
		}
		"npc_dota_custom_creep_12_2"	{
		}
		"npc_dota_custom_creep_13_1"	{	"1"	"my_druid_auras"
		}
		"npc_dota_custom_creep_13_2"	{	"1"	"my_lone_druid_true_form_datadriven"
		}
		"npc_dota_custom_creep_14_1"	{	"1"	"my_borrowed_time_datadriven"
		}
		"npc_dota_custom_creep_15_1"	{	"1"	"elder_titan_echo_stomp"		"2"	"elder_titan_ancestral_spirit"		"3"	"elder_titan_return_spirit"		"4"	"elder_titan_earth_splitter"		"5"	"my_bkb"		"6"	"my_agro"		"7"	"my_gem_datadriven"		"8"	"my_boss_hpdar"
		}
		"npc_dota_custom_creep_16_1"	{	"1"	"my_miss"
		}
		"npc_dota_custom_creep_17_1"	{	"1"	"my_chain_frost_datadriven"
		}
		"npc_dota_custom_creep_17_2"	{
		}
		"npc_dota_custom_creep_18_1"	{	"1"	"my_global_silence"
		}
		"npc_dota_custom_creep_19_1"	{	"1"	"my_alch"
		}
		"npc_dota_custom_creep_02_1"	{	"1"	"my_str_steel"
		}
		"npc_dota_custom_creep_02_2"	{	"1"	"undying_tombstone_zombie_deathstrike"
		}
		"npc_dota_custom_creep_20_1"	{	"1"	"phoenix_fire_spirits_datadriven"		"2"	"phoenix_launch_fire_spirit_datadriven"		"3"	"phoenix_sun_ray_datadriven"		"4"	"phoenix_supernova_datadriven"		"5"	"my_bkb"		"6"	"my_agro"		"7"	"my_gem_datadriven"		"8"	"my_boss_hpdar"
		}
		"npc_dota_custom_creep_21_1"	{	"1"	"slark_essence_shift_datadriven"		"2"	"slark_pounce"
		}
		"npc_dota_custom_creep_22_1"	{	"1"	"terrorblade_sunder"		"2"	"my_post_buff"
		}
		"npc_dota_custom_creep_23_1"	{
		}
		"npc_dota_custom_creep_23_2"	{	"1"	"berserkers_call_datadriven"		"2"	"culling_blade_datadriven"
		}
		"npc_dota_custom_creep_24_1"	{	"1"	"rupture_datadriven"
		}
		"npc_dota_custom_creep_24_2"	{	"1"	"tiny_toss"
		}
		"npc_dota_custom_creep_25_1"	{	"1"	"nyx_assassin_impale"		"2"	"nyx_assassin_spiked_carapace"		"3"	"nyx_assassin_vendetta"								"6"	"my_agro"		"7"	"my_gem_datadriven"		"8"	"my_boss_hpdar"
		}
		"npc_dota_custom_creep_26_1"	{	"1"	"arc_lightning_datadriven"		"2"	"lightning_bolt_datadriven"
		}
		"npc_dota_custom_creep_27_1"	{	"1"	"phantom_assassin_phantom_strike_datadriven"		"2"	"my_phantom_assassin_coup_de_grace_datadriven"
		}
		"npc_dota_custom_creep_28_1"	{	"1"	"huskar_berserkers_blood"		"2"	"burning_spear_datadriven"
		}
		"npc_dota_custom_creep_29_1"	{	"1"	"my_create_str_29_1"
		}
		"npc_dota_custom_creep_29_2"	{	"1"	"my_create_str_29_2"
		}
		"npc_dota_custom_creep_29_3"	{	"1"	"my_create_str_29_3"
		}
		"npc_dota_custom_creep_29_4"	{
		}
		"npc_dota_custom_creep_03_1"	{	"1"	"my_death_puls"
		}
		"npc_dota_custom_creep_30_1"	{	"1"	"chaos_bolt_datadriven"		"2"	"abyssal_underlord_firestorm"		"3"	"chaos_knight_chaos_strike"		"4"	"my_spectre_haunt"					"6"	"my_agro"		"7"	"my_gem_datadriven"		"8"	"my_boss_hpdar"
		}
		"npc_dota_custom_creep_31_1"	{	"5"	"techies_focused_detonate_datadriven"		"6"	"techies_remote_mines_datadriven"
		}
		"npc_dota_custom_creep_31_2"	{
		}
		"npc_dota_custom_creep_32_1"	{
		}
		"npc_dota_custom_creep_33_1"	{	"1"	"my_ibkb"
		}
		"npc_dota_custom_creep_34_1"	{	"1"	"spawnlord_aura"
		}
		"npc_dota_custom_creep_34_2"	{	"1"	"spawnlord_master_stomp"		"2"	"spawnlord_master_freeze"
		}
		"npc_dota_custom_creep_35_1"	{	"1"	"tinker_laser"		"2"	"tinker_heat_seeking_missile_datadriven"		"3"	"exorcism_datadriven"		"4"	"my_tinker_boom"					"6"	"my_agro"		"7"	"my_gem_datadriven"		"8"	"my_boss_hpdar"
		}
		"npc_dota_custom_creep_36_1"	{	"1"	"spectre_desolate"		"2"	"spectre_dispersion"
		}
		"npc_dota_custom_creep_37_1"	{	"1"	"my_kunkka_tidebringer"
		}
		"npc_dota_custom_creep_38_1"	{	"1"	"my_medusa_split_shot"		"2"	"special_bonus_unique_medusa_4"
		}
		"npc_dota_custom_creep_39_1"	{	"1"	"enchantress_untouchable"
		}
		"npc_dota_custom_creep_04_1"	{	"1"	"my_create_dva_new_1_1"
		}
		"npc_dota_custom_creep_04_1_1"	{	"1"	"my_create_dva_new_1_2"
		}
		"npc_dota_custom_creep_04_1_2"	{
		}
		"npc_dota_custom_creep_40_1"	{	"1"	"void_my_kupol"		"2"	"void_poliana"		"3"	"void_boom"		"4"	"void_molnii"		"5"	"void_mini_boom"		"6"	"my_agro"		"7"	"my_gem_datadriven"		"8"	"my_boss_hpdar"		"9"	"special_bonus_evasion_25"		"10"	"void_red"
		}
		"npc_dota_custom_creep_41_1"	{	"1"	"my_clinkz_strafe"
		}
		"npc_dota_custom_creep_42_1"	{	"1"	"my_earth_ult"
		}
		"npc_dota_custom_creep_43_1"	{	"1"	"necrolyte_heartstopper_aura"
		}
		"npc_dota_custom_creep_44_1"	{	"1"	"my_luna_moon_glaive"
		}
		"npc_dota_custom_creep_45_1"	{	"1"	"kotl_2_state"		"2"	"kotl_tether"		"3"	"kotl_boom"		"4"	"kotl_heal"		"5"	"kotl_3_state"		"6"	"my_agro"		"7"	"my_gem_datadriven"		"8"	"my_boss_hpdar"		"9"	"kotl_red"		"10"	"kotl_repel"		"11"	"special_bonus_evasion_25"		"12"	"kotl_mini_boom"
		}
		"npc_dota_custom_creep_45_2"	{	"1"	"kotl_wisp_state_pas"		"2"	"wisp_repel"		"3"	"my_gem_datadriven"		"4"	"kotl_tether"
		}
		"npc_dota_custom_creep_46_1"	{	"1"	"aba_shield"
		}
		"npc_dota_custom_creep_47_1"	{	"1"	"meepo_poof"
		}
		"npc_dota_custom_creep_48_1"	{	"1"	"life_stealer_feast"
		}
		"npc_dota_custom_creep_49_1"	{	"1"	"venomancer_venomous_gale_49_wave"		"2"	"venomancer_poison_sting_49_wave"
		}
		"npc_dota_custom_creep_49_2"	{
		}
		"npc_dota_custom_creep_05_1"	{	"1"	"05_spirits"		"2"	"05_ghost"											"6"	"my_agro"		"7"	"my_gem_datadriven"		"8"	"my_boss_hpdar"
		}
		"npc_dota_custom_creep_05_2"	{
		}
		"npc_dota_custom_creep_50_1"	{	"1"	"arc_warden_magnetic_field"		"2"	"od_pilon_creator"		"3"	"od_tree_breaker"		"4"	"od_poliana"		"5"	"od_mf"		"6"	"my_agro"		"7"	"my_gem_datadriven"		"8"	"my_boss_hpdar"		"9"	"od_battack"		"10"	"od_ult"		"11"	"special_bonus_evasion_25"
		}
		"npc_dota_custom_creep_51_1"	{	"1"	"dragon_aura"		"2"	"dragon_danger_run"		"3"	"dragon_ray_datadriven"		"4"	"deafening_blast_datadriven"		"5"	"dragon_sniper_ult"		"6"	"my_agro"		"7"	"my_gem_datadriven"		"8"	"my_boss_hpdar"		"9"	"dragon_elec_point"		"10"	"dragon_area_ignite"		"11"	"special_bonus_evasion_25"
		}
		"npc_dota_custom_creep_06_1"	{	"1"	"my_cent"
		}
		"npc_dota_custom_creep_06_2"	{
		}
		"npc_dota_custom_creep_07_1"	{	"1"	"my_invisibility"
		}
		"npc_dota_custom_creep_08_1"	{	"1"	"bandit_archer_arrow"
		}
		"npc_dota_custom_creep_08_2"	{
		}
		"npc_dota_custom_creep_09_1"	{	"1"	"my_spider_create_minions"		"2"	"venomancer_poison_sting"
		}
		"npc_dota_custom_creep_09_2"	{	"1"	"my_broodmother_incapacitating_bite"
		}
		"npc_dota_custom_creep_09_3"	{	"1"	"burrower_explosion"		"2"	"my_red"
		}
		"npc_dota_elder_titan_ancestral_spirit"	{	"1"	"elder_titan_echo_stomp_spirit"		"2"	"elder_titan_return_spirit"
		}
		"npc_dota_fire_trap_ward"	{	"1"	"breathe_fire"		"2"	"trap_unselectable"
		}
		"npc_dota_gold_spirit"	{	"1"	"my_pick_gold"
		}
		"npc_dota_kobold_overboss"	{	"1"	"dota_ability_throw_coin"		"2"	"dota_ability_throw_coin_long"		"3"	"dota_ability_celebrate"
		}
		"npc_dota_kobold_radiantboss"	{	"1"	"dota_ability_throw_coin"		"2"	"dota_ability_throw_coin_long"		"3"	"dota_ability_celebrate"
		}
		"npc_dota_kobold_underboss"	{	"1"	"dota_ability_throw_coin"		"2"	"dota_ability_throw_coin_long"		"3"	"dota_ability_celebrate"
		}
		"npc_dota_lycan_wolf5"	{	"1"	"lycan_summon_wolves_critical_strike"		"2"	"lycan_summon_wolves_invisibility"
		}
		"npc_dota_lycan_wolf6"	{	"1"	"lycan_summon_wolves_critical_strike"		"2"	"lycan_summon_wolves_invisibility"
		}
		"npc_dota_lycan_wolf7"	{	"1"	"lycan_summon_wolves_critical_strike"		"2"	"lycan_summon_wolves_invisibility"
		}
		"npc_dota_my_point"	{	"1"	"mod_my_points"
		}
		"npc_dota_pendulum_trap_ward"	{	"1"	"pendulum_trap"		"2"	"trap_unselectable"
		}
		"npc_dota_spike_trap_ward"	{	"1"	"spike_trap"		"2"	"trap_unselectable"
		}
		"npc_dota_treasure_courier"	{	"1"	"dota_ability_treasure_courier"
		}
		"npc_dota_venom_trap_ward"	{	"1"	"breathe_poison"		"2"	"trap_unselectable"
		}
		"npc_dota_xp_global"	{	"1"	"dota_ability_xp_global"
		}
		"npc_dota_xp_granter"	{	"1"	"dota_ability_xp_granter"
		}
		"npc_dota_xp_granter2"	{	"1"	"dota_ability_xp_granter2"
		}
		"npc_vision_revealer"	{	"1"	"dota_ability_vision_revealer"		"2"	"dota_ability_reveal_invis"
		}
	}
